# Default application properties.
# 
# Create an application.yml on your working directory to override these values,
# or application-X.yml where X is the name of the active profile provided via
# the JVM argument -Dspring.profiles.active=X

# Default profile (tests)
logging:
  pattern:
    console: "%d{HH:mm:ss} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file:  "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org.snf: DEBUG

app:
  datasource:
    kb:
      url: jdbc:mariadb://localhost:3306/killbill
      username: killbill
      password: killbill
      driveClassName: com.mysql.cj.jdbc.Driver
    sn:
      url: jdbc:postgresql://localhost:5496/solarnetwork_stage
      username: solarnet
      password: solarnet
      driverClassName: org.postgresql.Driver
    

---
spring:
  profiles: development
  
app:
  datasource:
    kb:
      url: jdbc:mariadb://localhost:3306/killbill
      username: killbill
      password: killbill
      driveClassName: com.mysql.cj.jdbc.Driver
    sn:
      url: jdbc:postgresql://localhost:5496/solarnetwork
      username: solarnet
      password: solarnet
      driverClassName: org.postgresql.Driver

logging:
  level:
    org.snf: INFO

---
spring:
  profiles: production

logging:
  level:
    org.snf: INFO
    